// @vitest-environment happy-dom
// Plan 02-03 Task 3 — PatientForm tests.
// Per PAT-01 (create) + PAT-03 (edit).
//
// Quick task 20260812 — MRN is auto-generated by the repo (migration 0008
// + nextMrn). The PatientForm no longer carries an MRN input on either
// mode; the create flow submits without mrn and the edit flow shows the
// existing MRN as a read-only label.

import { describe, expect, it, beforeEach } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { getApi } from '../setup';
import { initialRoute, setRoute } from '@/lib/router';
import { session } from '@/store/session';
import PatientForm from '@/pages/PatientForm';
import type { Patient } from '@shared/ipc-contract';

const existingPatient: Patient = {
  id: '00000000-0000-4000-8000-000000000010',
  fullName: 'Alice Carter',
  dob: '1980-04-12',
  gender: 'female',
  mrn: 'MRN-000001',
  phone: '555-0001',
  notes: 'initial notes',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  deletedAt: null,
};

function setAdminSession(): void {
  const api = getApi();
  api.auth.status.mockResolvedValue({
    hasUsers: true,
    authenticated: true,
    userId: '00000000-0000-4000-8000-000000000099',
    clinicName: 'Cairo',
    isFirstAdmin: true,
  });
  api.auth.usersList.mockResolvedValue([
    {
      id: '00000000-0000-4000-8000-000000000099',
      fullName: 'Dr. Layla',
      isFirstAdmin: true,
      lastLoginAt: Date.now(),
      failedAttempts: 0,
      lockedUntil: null,
    },
  ]);
}

beforeEach(() => {
  setRoute(initialRoute);
  setAdminSession();
  void session.refresh();
});

describe('PatientForm (create mode)', () => {
  it('submits valid fields without an MRN input and calls patients.create once', async () => {
    const api = getApi();
    api.patients.create.mockResolvedValue({
      id: '00000000-0000-4000-8000-000000000777',
      fullName: 'Carol Diaz',
      dob: '1990-01-15',
      gender: 'female',
      mrn: 'MRN-000999',
      phone: '555-9999',
      notes: 'new',
      createdAt: Date.now(),
      updatedAt: Date.now(),
      deletedAt: null,
    });
    const user = userEvent.setup();
    render(<PatientForm mode="create" />);
    await user.type(screen.getByLabelText(/full name/i), 'Carol Diaz');
    await user.type(screen.getByLabelText(/date of birth/i), '1990-01-15');
    // No MRN input — auto-generated by the repo.
    expect(screen.queryByLabelText(/^mrn$/i)).toBeNull();
    await user.type(screen.getByLabelText(/^phone$/i), '555-9999');
    await user.type(screen.getByLabelText(/^notes$/i), 'new');
    await user.click(screen.getByRole('button', { name: /create patient/i }));
    await waitFor(() => expect(api.patients.create).toHaveBeenCalledTimes(1));
    expect(api.patients.create).toHaveBeenCalledWith({
      fullName: 'Carol Diaz',
      dob: '1990-01-15',
      gender: null,
      phone: '555-9999',
      notes: 'new',
    });
  });
});

describe('PatientForm (edit mode)', () => {
  it('renders the existing MRN as a read-only label and never sends it back in the patch', async () => {
    const api = getApi();
    api.patients.get.mockResolvedValue(existingPatient);
    api.patients.update.mockResolvedValue({ ...existingPatient, fullName: 'Alice C.' });
    const user = userEvent.setup();
    render(<PatientForm mode="edit" patientId={existingPatient.id} />);
    // wait for the form to load
    const fullNameInput = await screen.findByLabelText(/full name/i);
    await waitFor(() => expect(fullNameInput).toHaveValue('Alice Carter'));
    // MRN is shown read-only — not an input field.
    await screen.findByTestId('patient-mrn-readonly');
    expect(screen.queryByLabelText(/^mrn$/i)).toBeNull();
    await user.clear(fullNameInput);
    await user.type(fullNameInput, 'Alice C.');
    await user.click(screen.getByRole('button', { name: /save changes/i }));
    await waitFor(() => expect(api.patients.update).toHaveBeenCalledTimes(1));
    const [idArg, patchArg] = api.patients.update.mock.calls[0] ?? [];
    expect(idArg).toBe(existingPatient.id);
    expect(patchArg).toMatchObject({ fullName: 'Alice C.' });
    // The patch must NOT carry an mrn — the validator's .strict() would
    // reject it anyway, but we lock the contract at the call site.
    expect(patchArg).not.toHaveProperty('mrn');
  });

  it('shows inline validation when DOB is empty (zod regex rejects it on submit)', async () => {
    const api = getApi();
    api.patients.get.mockResolvedValue(existingPatient);
    const user = userEvent.setup();
    render(<PatientForm mode="edit" patientId={existingPatient.id} />);
    const dob = await screen.findByLabelText(/date of birth/i);
    await user.clear(dob);
    await user.click(screen.getByRole('button', { name: /save changes/i }));
    await waitFor(() => expect(screen.getByLabelText(/date of birth/i)).toHaveAttribute('aria-invalid', 'true'));
    expect(api.patients.update).not.toHaveBeenCalled();
  });
});