// patients table repository — cached prepared statements only (per anti-pattern: no raw SQL in repos).
// Per PAT-01/02/03/04 + AUDIT-01 + Fix 6.

import type Database from 'better-sqlite3';
import { randomUUID } from 'node:crypto';
import { getDb } from './index';
import type { Patient } from '@shared/ipc-contract';
import { IpcErrorException, ipcError } from '@shared/errors';

// Internal row shape (snake_case columns). Converted to `Patient` (camelCase) at the repo boundary
// so the IPC layer + tests don't need a separate mapper.
// Quick task 20260812 — mrn is auto-generated by nextMrn() at insert time
// (NOT NULL via migration 0008). The previous `string | null` is gone.
export type PatientRow = {
  id: string;
  full_name: string;
  dob: string;
  gender: 'male' | 'female' | 'other' | null;
  mrn: string;
  phone: string | null;
  notes: string | null;
  created_at: number;
  updated_at: number;
  deleted_at: number | null;
};

export type PatientCreateInput = {
  fullName: string;
  dob: string;
  gender: 'male' | 'female' | 'other' | null;
  phone: string | null;
  notes: string | null;
};

// Quick task 20260812 — `mrn` removed from the patchable surface. mrn is
// auto-generated at create time (per migration 0008) and never editable;
// the validator's `.strict()` rejects any stray `mrn` in the patch.
export type PatientPatchInput = Partial<Pick<Patient, 'fullName' | 'dob' | 'gender' | 'phone' | 'notes'>>;

export type PatientListInput = {
  search?: string;
  mrn?: string;
  includeDeleted?: boolean;
  // Phase 7 / Plan 07-02 — SRCH-01..03 + D-02: cross-cutting Patient
  // List filters. dateFrom/dateTo are yyyy-mm-dd strings parsed to ms
  // bounds against procedures.started_at (canonical procedure date per
  // Phase 4 D-10). doctorId filters on procedures.doctor_id.
  // procedureStatus is a multi-select against procedures.status. All
  // four are AND-combined (per D-02 verbatim). Empty/missing = no
  // constraint (preserves Phase 2 zero-config behavior).
  dateFrom?: string;
  dateTo?: string;
  doctorId?: string;
  procedureStatus?: ('recording' | 'completed' | 'partial' | 'crashed')[];
  page?: number;
  pageSize?: number;
};

type Stmt = Database.Statement;

let cached: {
  insert: Stmt;
  get: Stmt;
  getIncludingDeleted: Stmt;
  listActive: Stmt;
  listAll: Stmt;
  countActive: Stmt;
  countAll: Stmt;
  listByMrnActive: Stmt;
  listByMrnAll: Stmt;
  countByMrnActive: Stmt;
  countByMrnAll: Stmt;
  listBySearchActive: Stmt;
  listBySearchAll: Stmt;
  countBySearchActive: Stmt;
  countBySearchAll: Stmt;
  // Phase 7 / Plan 07-02 — SRCH-01..03 + D-02: single combined
  // prepared statement for the AND-combined filter matrix (search +
  // MRN + dateFrom/dateTo + doctorId + procedureStatus). Per
  // RESEARCH.md Pattern 1 "no per-filter statement explosion" — one
  // prepared statement handles every combination via optional
  // parameters + an EXISTS subquery against procedures.
  listWithFiltersActive: Stmt;
  listWithFiltersAll: Stmt;
  countWithFiltersActive: Stmt;
  countWithFiltersAll: Stmt;
  // Quick task 20260812 — auto-MRN counter (migration 0008). nextMrn is
  // read-then-bumped inside the caller's db.transaction() so two
  // concurrent creates can't collide (better-sqlite3 is sync but the
  // atomicity guarantee still has to come from the transaction).
  nextMrn: Stmt;
  bumpMrn: Stmt;
  update: Stmt;
  softDelete: Stmt;
  restore: Stmt;
} | null = null;

function stmts() {
  if (cached) return cached;
  const db = getDb();
  cached = {
    insert: db.prepare(
      `INSERT INTO patients (id, full_name, dob, gender, mrn, phone, notes, created_at, updated_at, deleted_at)
       VALUES (@id, @full_name, @dob, @gender, @mrn, @phone, @notes, @created_at, @updated_at, NULL)`,
    ),
    get: db.prepare('SELECT * FROM patients WHERE id = ? AND deleted_at IS NULL'),
    getIncludingDeleted: db.prepare('SELECT * FROM patients WHERE id = ?'),
    listActive: db.prepare(
      'SELECT * FROM patients WHERE deleted_at IS NULL ORDER BY full_name COLLATE NOCASE LIMIT @limit OFFSET @offset',
    ),
    listAll: db.prepare(
      'SELECT * FROM patients ORDER BY full_name COLLATE NOCASE LIMIT @limit OFFSET @offset',
    ),
    countActive: db.prepare('SELECT COUNT(*) AS c FROM patients WHERE deleted_at IS NULL'),
    countAll: db.prepare('SELECT COUNT(*) AS c FROM patients'),
    listByMrnActive: db.prepare(
      'SELECT * FROM patients WHERE deleted_at IS NULL AND mrn = @mrn ORDER BY full_name COLLATE NOCASE LIMIT @limit OFFSET @offset',
    ),
    listByMrnAll: db.prepare(
      'SELECT * FROM patients WHERE mrn = @mrn ORDER BY full_name COLLATE NOCASE LIMIT @limit OFFSET @offset',
    ),
    countByMrnActive: db.prepare(
      'SELECT COUNT(*) AS c FROM patients WHERE deleted_at IS NULL AND mrn = @mrn',
    ),
    countByMrnAll: db.prepare('SELECT COUNT(*) AS c FROM patients WHERE mrn = @mrn'),
    listBySearchActive: db.prepare(
      `SELECT * FROM patients
       WHERE deleted_at IS NULL AND full_name LIKE @search COLLATE NOCASE
       ORDER BY full_name COLLATE NOCASE LIMIT @limit OFFSET @offset`,
    ),
    listBySearchAll: db.prepare(
      `SELECT * FROM patients
       WHERE full_name LIKE @search COLLATE NOCASE
       ORDER BY full_name COLLATE NOCASE LIMIT @limit OFFSET @offset`,
    ),
    countBySearchActive: db.prepare(
      `SELECT COUNT(*) AS c FROM patients WHERE deleted_at IS NULL AND full_name LIKE @search COLLATE NOCASE`,
    ),
    countBySearchAll: db.prepare(
      `SELECT COUNT(*) AS c FROM patients WHERE full_name LIKE @search COLLATE NOCASE`,
    ),
    // listWithFiltersActive — single statement handles all filter combos
    // (SRCH-01..03 + D-02 AND-combined). @search / @mrn are NULL when no
    // name/MRN filter; @dateFromMs / @dateToMs are NULL when no date
    // range; @doctorId is NULL when no doctor filter; @hasStatus is
    // 0/1 and @status0..@status3 are populated only when @hasStatus=1.
    // The EXISTS subquery guarantees the predicate applies to procedures
    // (per D-02: date range applies to procedures.started_at, doctorId
    // applies to procedures.doctor_id, procedureStatus is a multi-select
    // across procedures.status). Patients WITHOUT any matching
    // procedure are excluded when any of the procedure-bound filters
    // are set — matches the doctor's mental model of "find the patients
    // whose procedures match these constraints".
    //
    // ponytail: "WHERE 1=1 AND" anchor lets us conditionally append
    // clauses via the @searchTrimmed / @mrnTrimmed / @hasProcedures
    // trick (each predicate evaluates to TRUE when the corresponding
    // param is NULL/sentinel). This avoids the combinatorial explosion
    // that a per-filter statement set would create.
    listWithFiltersActive: db.prepare(
      `SELECT * FROM patients
       WHERE deleted_at IS NULL
         AND (@searchTrimmed = '' OR full_name LIKE @search COLLATE NOCASE)
         AND (@mrnTrimmed = '' OR mrn = @mrn)
         AND (
           @hasProcedures = 0
           OR EXISTS (
             SELECT 1 FROM procedures
             WHERE procedures.patient_id = patients.id
               AND (@dateFromMs IS NULL OR procedures.started_at >= @dateFromMs)
               AND (@dateToMs IS NULL OR procedures.started_at <= @dateToMs)
               AND (@doctorId IS NULL OR procedures.doctor_id = @doctorId)
               AND (@hasStatus = 0 OR procedures.status IN (@status0, @status1, @status2, @status3))
           )
         )
       ORDER BY full_name COLLATE NOCASE LIMIT @limit OFFSET @offset`,
    ),
    listWithFiltersAll: db.prepare(
      `SELECT * FROM patients
       WHERE (@searchTrimmed = '' OR full_name LIKE @search COLLATE NOCASE)
         AND (@mrnTrimmed = '' OR mrn = @mrn)
         AND (
           @hasProcedures = 0
           OR EXISTS (
             SELECT 1 FROM procedures
             WHERE procedures.patient_id = patients.id
               AND (@dateFromMs IS NULL OR procedures.started_at >= @dateFromMs)
               AND (@dateToMs IS NULL OR procedures.started_at <= @dateToMs)
               AND (@doctorId IS NULL OR procedures.doctor_id = @doctorId)
               AND (@hasStatus = 0 OR procedures.status IN (@status0, @status1, @status2, @status3))
           )
         )
       ORDER BY full_name COLLATE NOCASE LIMIT @limit OFFSET @offset`,
    ),
    countWithFiltersActive: db.prepare(
      `SELECT COUNT(*) AS c FROM patients
       WHERE deleted_at IS NULL
         AND (@searchTrimmed = '' OR full_name LIKE @search COLLATE NOCASE)
         AND (@mrnTrimmed = '' OR mrn = @mrn)
         AND (
           @hasProcedures = 0
           OR EXISTS (
             SELECT 1 FROM procedures
             WHERE procedures.patient_id = patients.id
               AND (@dateFromMs IS NULL OR procedures.started_at >= @dateFromMs)
               AND (@dateToMs IS NULL OR procedures.started_at <= @dateToMs)
               AND (@doctorId IS NULL OR procedures.doctor_id = @doctorId)
               AND (@hasStatus = 0 OR procedures.status IN (@status0, @status1, @status2, @status3))
           )
         )`,
    ),
    countWithFiltersAll: db.prepare(
      `SELECT COUNT(*) AS c FROM patients
       WHERE (@searchTrimmed = '' OR full_name LIKE @search COLLATE NOCASE)
         AND (@mrnTrimmed = '' OR mrn = @mrn)
         AND (
           @hasProcedures = 0
           OR EXISTS (
             SELECT 1 FROM procedures
             WHERE procedures.patient_id = patients.id
               AND (@dateFromMs IS NULL OR procedures.started_at >= @dateFromMs)
               AND (@dateToMs IS NULL OR procedures.started_at <= @dateToMs)
               AND (@doctorId IS NULL OR procedures.doctor_id = @doctorId)
               AND (@hasStatus = 0 OR procedures.status IN (@status0, @status1, @status2, @status3))
           )
         )`,
    ),
    // Quick task 20260812 — auto-MRN counter. Read current `next`, then
    // bump; both statements must run inside the same db.transaction()
    // as the patient insert. See nextMrn() below.
    nextMrn: db.prepare('SELECT next FROM patient_mrn_counter WHERE id = 1'),
    bumpMrn: db.prepare('UPDATE patient_mrn_counter SET next = next + 1 WHERE id = 1'),
    update: db.prepare(
      `UPDATE patients
       SET full_name = @full_name, dob = @dob, gender = @gender,
           mrn = @mrn, phone = @phone, notes = @notes, updated_at = @updated_at
       WHERE id = @id AND deleted_at IS NULL`,
    ),
    // ponytail: softDelete is the only deletion path (per PAT-04). No DELETE FROM patients exists anywhere.
    softDelete: db.prepare(
      'UPDATE patients SET deleted_at = ?, updated_at = ? WHERE id = ? AND deleted_at IS NULL',
    ),
    restore: db.prepare(
      'UPDATE patients SET deleted_at = NULL, updated_at = ? WHERE id = ? AND deleted_at IS NOT NULL',
    ),
  };
  return cached;
}

// ponytail: tests swap DB instances between cases, so cached statements must be dropped.
export function __resetPatientRepoCache(): void {
  cached = null;
}

// Quick task 20260812 — auto-MRN. read+update is two statements, so this
// MUST be called inside the caller's db.transaction() (which the IPC
// createPatient handler already provides). better-sqlite3 is sync +
// single-threaded, so a bare read-then-write without the txn would race.
function nextMrn(): string {
  const row = stmts().nextMrn.get() as { next: number } | undefined;
  if (!row) throw new Error('patient_mrn_counter missing — migration 0008 not applied');
  stmts().bumpMrn.run();
  return `MRN-${String(row.next).padStart(6, '0')}`;
}

function rowToPatient(row: PatientRow): Patient {
  return {
    id: row.id,
    fullName: row.full_name,
    dob: row.dob,
    gender: row.gender,
    mrn: row.mrn,
    phone: row.phone,
    notes: row.notes,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    deletedAt: row.deleted_at,
  };
}

const MAX_PAGE_SIZE = 200;

export const patientRepo = {
  // Quick task 20260812 — mrn is auto-generated inside the caller's txn
  // (nextMrn → insert), so no SQLITE_CONSTRAINT_UNIQUE translation is
  // needed: there's no user-supplied MRN to collide anymore.
  create(input: PatientCreateInput): Patient {
    const id = randomUUID();
    const now = Date.now();
    const mrn = nextMrn(); // called inside the caller's txn
    stmts().insert.run({
      id,
      full_name: input.fullName,
      dob: input.dob,
      gender: input.gender,
      mrn,
      phone: input.phone,
      notes: input.notes,
      created_at: now,
      updated_at: now,
    });
    const created = stmts().getIncludingDeleted.get(id) as PatientRow | undefined;
    if (!created) {
      throw new Error('patient row missing immediately after insert');
    }
    return rowToPatient(created);
  },

  get(id: string): Patient | undefined {
    const row = stmts().get.get(id) as PatientRow | undefined;
    return row ? rowToPatient(row) : undefined;
  },

  // ponytail: include-deleted variant is reserved for restore + admin audit review (per T-02-PAT-01).
  getIncludingDeleted(id: string): Patient | undefined {
    const row = stmts().getIncludingDeleted.get(id) as PatientRow | undefined;
    return row ? rowToPatient(row) : undefined;
  },

  list(filter: PatientListInput): { rows: Patient[]; total: number } {
    const page = filter.page && filter.page > 0 ? filter.page : 1;
    const pageSize = filter.pageSize && filter.pageSize > 0 ? filter.pageSize : 25;
    const limit = Math.min(pageSize, MAX_PAGE_SIZE);
    const offset = (page - 1) * limit;
    const includeDeleted = filter.includeDeleted === true;
    const hasSearch = !!filter.search && filter.search.length > 0;
    const hasMrn = !!filter.mrn && filter.mrn.length > 0;

    // Phase 7 / Plan 07-02 — SRCH-01..03 + D-02: any of dateFrom,
    // dateTo, doctorId, procedureStatus forces the AND-combined path
    // via the EXISTS subquery. The Phase 2 zero-config surface (no
    // filters set) still routes through the original single-column
    // statements — no DB change when the new surface is unused.
    const hasDateFrom = !!filter.dateFrom && filter.dateFrom.length > 0;
    const hasDateTo = !!filter.dateTo && filter.dateTo.length > 0;
    const hasDoctorId = !!filter.doctorId;
    const hasStatus = !!filter.procedureStatus && filter.procedureStatus.length > 0;
    const hasProceduresFilter = hasDateFrom || hasDateTo || hasDoctorId || hasStatus;

    if (!hasProceduresFilter) {
      // Phase 2 fast path — preserves the existing single-column
      // statements so the common case (no cross-cutting filter) stays
      // on the simple queries.
      let listStmt: Stmt;
      let countStmt: Stmt;
      const params: Record<string, unknown> = { limit, offset };

      if (hasMrn) {
        params.mrn = filter.mrn;
        listStmt = includeDeleted ? stmts().listByMrnAll : stmts().listByMrnActive;
        countStmt = includeDeleted ? stmts().countByMrnAll : stmts().countByMrnActive;
      } else if (hasSearch) {
        params.search = `%${filter.search}%`;
        listStmt = includeDeleted ? stmts().listBySearchAll : stmts().listBySearchActive;
        countStmt = includeDeleted ? stmts().countBySearchAll : stmts().countBySearchActive;
      } else {
        listStmt = includeDeleted ? stmts().listAll : stmts().listActive;
        countStmt = includeDeleted ? stmts().countAll : stmts().countActive;
      }

      const rows = listStmt.all(params) as PatientRow[];
      const total = (countStmt.get(params) as { c: number }).c;
      return { rows: rows.map(rowToPatient), total };
    }

    // Phase 7 combined path — single prepared statement handles every
    // AND-combined filter combo (SRCH-01..03 + D-02). The @searchTrimmed
    // and @mrnTrimmed sentinels let the EXISTS subquery be bypassed when
    // no procedure-bound filter is set (preserves the no-procedure case
    // for the legacy search-only filter combo).
    const dateFromMs = hasDateFrom ? Date.parse(`${filter.dateFrom}T00:00:00.000Z`) : null;
    const dateToMs = hasDateTo
      ? Date.parse(`${filter.dateTo}T23:59:59.999Z`)
      : null;
    const params2: Record<string, unknown> = {
      limit,
      offset,
      // @searchTrimmed / @mrnTrimmed — empty string means "no constraint"
      // (matches the WHERE clause's `= ''` short-circuit). Search uses
      // LIKE '%value%' so trim + percent-wrap happens here.
      search: hasSearch ? `%${filter.search}%` : '%',
      searchTrimmed: hasSearch ? 'x' : '',
      mrn: hasMrn ? filter.mrn : '',
      mrnTrimmed: hasMrn ? 'x' : '',
      dateFromMs,
      dateToMs,
      doctorId: filter.doctorId ?? null,
      hasStatus: hasStatus ? 1 : 0,
      // Status array slot 0..3 — populated only when @hasStatus=1; the
      // IN clause matches 1, 2, 3, or 4 of them; empty slots are
      // coerced to a sentinel that the IN clause skips via !=@status0.
      status0: hasStatus && filter.procedureStatus![0] ? filter.procedureStatus![0] : null,
      status1: hasStatus && filter.procedureStatus![1] ? filter.procedureStatus![1] : null,
      status2: hasStatus && filter.procedureStatus![2] ? filter.procedureStatus![2] : null,
      status3: hasStatus && filter.procedureStatus![3] ? filter.procedureStatus![3] : null,
    };

    // @hasProcedures sentinel — short-circuits the EXISTS subquery when
    // none of the procedure-bound filters are set. This keeps the
    // combined path correct for the "search by name + status filter
    // omitted" case (search applies, procedure EXISTS does NOT).
    params2.hasProcedures = hasProceduresFilter ? 1 : 0;

    const listStmt = includeDeleted ? stmts().listWithFiltersAll : stmts().listWithFiltersActive;
    const countStmt = includeDeleted ? stmts().countWithFiltersAll : stmts().countWithFiltersActive;
    const rows = listStmt.all(params2) as PatientRow[];
    const total = (countStmt.get(params2) as { c: number }).c;
    return { rows: rows.map(rowToPatient), total };
  },

  update(id: string, patch: PatientPatchInput): Patient {
    const current = stmts().getIncludingDeleted.get(id) as PatientRow | undefined;
    if (!current || current.deleted_at !== null) {
      throw new IpcErrorException(ipcError('IPC_NOT_FOUND', 'Patient not found'));
    }
    // Quick task 20260812 — mrn intentionally NOT read from patch; the
    // auto-generated mrn is immutable post-insert. The validator's
    // .strict() rejects a stray `mrn` in the patch, so we never see one
    // here. merged.mrn stays = current.mrn and the update SQL's
    // `mrn = @mrn` binding writes back the same value (no-op).
    const merged: PatientRow = {
      ...current,
      full_name: patch.fullName ?? current.full_name,
      dob: patch.dob ?? current.dob,
      gender: patch.gender === undefined ? current.gender : patch.gender,
      phone: patch.phone === undefined ? current.phone : patch.phone,
      notes: patch.notes === undefined ? current.notes : patch.notes,
      updated_at: Date.now(),
    };
    stmts().update.run({
      id,
      full_name: merged.full_name,
      dob: merged.dob,
      gender: merged.gender,
      mrn: merged.mrn,
      phone: merged.phone,
      notes: merged.notes,
      updated_at: merged.updated_at,
    });
    const refreshed = stmts().getIncludingDeleted.get(id) as PatientRow;
    return rowToPatient(refreshed);
  },

  // per PAT-04 — soft delete only. rowcount > 0 is the success signal.
  softDelete(id: string): boolean {
    const now = Date.now();
    const result = stmts().softDelete.run(now, now, id);
    return result.changes > 0;
  },

  // per D-02 + PAT-04 — restore is admin-gated at the IPC layer; this is just the SQL.
  restore(id: string): boolean {
    const now = Date.now();
    const result = stmts().restore.run(now, id);
    return result.changes > 0;
  },
};